<?php
/**
 * compose_newwindow - Compose(Reply/Forward) in a New Window
 *
 * @version 1.05 (20100212)
 * @author Karl McMurdo (user xrxca on roundcubeforum.net)
 * @url http://github.com/xrxca/cnw
 * @copyright (c) 2010 Karl McMurdo
 *
 */
$labels = array();

$labels['compose_newwindow'] = 'Compose in New Window';
$labels['enabled'] = 'Enable compose in new window';
$labels['hidebar'] = 'Hide main toolbar in compose windows';
$labels['allwindows'] = 'Use new window for ALL message compose windows';
$labels['allwindows_warning'] = 'This may cause issues with some browser popup blockers.';
?>
