<?php
/**
 * compose_newwindow - Compose(Reply/Forward) in a New Window
 *
 * @version 3.00 (20110822)
 * @author Karl McMurdo (user xrxca on roundcubeforum.net)
 * @url http://github.com/xrxca/cnw
 * @copyright (c) 2010-2011 Karl McMurdo
 *
 */
$labels = array();

$labels['compose_newwindow'] = 'Redactar en una ventana nueva';
$labels['enabled'] = 'Activar la redacción en una ventana nueva';
$labels['hidebar'] = 'Ocultar la barra de herramientas en las ventanas de redacción';
?>
