<?php
/*
+-----------------------------------------------------------------------+
| language/fr_FR/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Anthony Prades <anthony.prades@blue-mind.net                  |
+-----------------------------------------------------------------------+
*/

$labels = array();
$labels['compose_newwindow'] = 'Composer dans une nouvelle fenêtre';
$labels['enabled'] = 'Activer la composition dans une nouvelle fenêtre';
$labels['hidebar'] = 'Cacher la barre d\'outil principale dans la fenêtre de composition';

?>
